### ISSUE TITLE
how to config the password of redis?

### ISSUE THREAD

**Issue by leokoon** [jcoleman/tomcat-redis-session-manager#100]

**Comment by luyuanwan** [comment]
<Valve className="com.orangefunction.tomcat.redissessions.RedisSessionHandlerValve" />
<Manager className="com.orangefunction.tomcat.redissessions.RedisSessionManager"
         host="localhost" 
         port="6379" 
         password="123456" 
         database="0" 
         maxInactiveInterval="60" 
         sessionPersistPolicies="PERSIST_POLICY_1,PERSIST_POLICY_2,.." 
         sentinelMaster="SentinelMasterName" 
         sentinels="sentinel-host-1:port,sentinel-host-2:port,.."  />
