### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by ajstokar** [jcoleman/tomcat-redis-session-manager#12]
I am trying to implement your project and am getting this error when I startup tomcat:

java.lang.UnsupportedClassVersionError: com/radiadesign/catalina/session/RedisSessionHandlerValve : Unsupported major.minor version 51.0

Using 
Tomcat 6
jedis-2.1.0.jar
tomcat-redis-session-manager-1.2-tomcat-6.jar

[root@ip-10-28-29-162 logs]# java -version
java version "1.6.0_24"
OpenJDK Runtime Environment (IcedTea6 1.11.3) (amazon-52.1.11.3.45.amzn1-x86_64)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)

**Comment by luomoxiaozi** [comment]
@ajstokar, Your answer is right.I solve the same problem with your answer.
