### ISSUE TITLE
Servlet 3+ async requests support

### ISSUE THREAD

**Issue by javax1** [jcoleman/tomcat-redis-session-manager#17]
Does tomcat-redis-session-manager support Servlet 3+ async requests? Is that enough to change RedisSessionHandlerValve constuctors to allow putting requests in async mode? 
I.e.
    public RedisSessionHandlerValve() {
      super(true); // instead of super();
    }

which will call

```
public ValveBase() {
    this(false);
}

public ValveBase(boolean asyncSupported) {
    this.asyncSupported = asyncSupported;
}
```

**Comment by vipshuanshuan** [comment]
Hello,does tomcat-redis-session-manager support Servlet 3+ async requests?
