### ISSUE TITLE
Compile failed with Tomcat 8

### ISSUE THREAD

**Issue by MingleiLee** [jcoleman/tomcat-redis-session-manager#61]
In RedisSessionManager.java, Line 716:

     if (getContainer() != null) {
      loader = getContainer().getLoader();
    }

The getLoader() method is removed in Tomcat 8.

**Comment by tcollins** [comment]
Any plan or timeline on adding tomcat 8 support?  Thanks.

**Comment by jcoleman** [comment]
Same response as #50:

Tomcat 8 is not currently supported and has not been tested or developed for at all.

I currently don't have the time to add Tomcat 8 support in my spare time. However if you're interested in Tomcat 8 support for your particular use case and/or business, as the README notes, I'm available as a consultancy on a contractual basis. If you'd like to pursue getting this feature added at a contract rate (and gain some commercial support as well), feel free to contact me at james@orangefunction.com.

**Comment by shimonmagal** [comment]
Kind of old, but may still help someone.
Just change getContainer() --> getContext()

I needed support for tomcat 8, so this is a release I created off a fork.

https://github.com/shimonmagal/tomcat-redis-session-manager/releases/tag/1.2-tomcat-8

**Comment by alwinmark** [comment]
Hi @jcoleman. There are lots of people like my former company that are using your Manager for Tomcat 8 allready (while they forked it).

Maybe should create a branch or transfer officially the project to one of those so they can take care about that.
