### ISSUE TITLE
Java 6 support

### ISSUE THREAD

**Issue by asundaram** [jcoleman/tomcat-redis-session-manager#69]
I am trying to setup redis tomcat session provider in the following environment - Tomcat 1.7 and JDK 1.6. Based on the documentation I have built war file from tomcat-7 branch. Basic setup is functional, but some areas of the application do not work as expected because of the dirty tracking. 

I tried to set Persistence Policies with both options "SAVE_ON_CHANGE" and "ALWAYS_SAVE_AFTER_REQUEST", but looks like the Persistence Policies are not implemented in the tomcat-7 branch. On Tomcat startup I am getting this "WARNING: [SetPropertiesRule]{Context/Manager} Setting property 'sessionPersistPolicies' to 'SAVE_ON_CHANGE,ALWAYS_SAVE_AFTER_REQUEST' did not find a matching property."

I tried to set the session change tracking using RedisSession.setManualDirtyTrackingSupportEnabled(true), but looks like there is no way to set this because the method is non-static in tomcat-7 branch and there is no way to cast the session object to a RedisSession. In the master branch I see the method is static.

Am I missing something here or is the support for Java 6 deprecated?

**Comment by jcoleman** [comment]
The tomcat-7 branch was merged into master before those features were added.

Java 6 support has been deprecated, yes.

**Comment by niejian** [comment]
but I try to use tomcat-redis-session-manager-1.2-tomcat-6  it  came java.lang.VerifyError: class com.radiadesign.catalina.session.RedisSessionManager overrides final method start.()V

**Comment by jcoleman** [comment]
@niejian See the README for what versions of Java and Tomcat are supported: https://github.com/jcoleman/tomcat-redis-session-manager#tomcat-versions
