### ISSUE TITLE
RedisSession throw NullPointException

### ISSUE THREAD

**Issue by RishonLi** [jcoleman/tomcat-redis-session-manager#70]
in the method setAttribute 

`if ( (value != null || oldValue != null)`
`         && ( value == null && oldValue != null`
`              || oldValue == null && value != null`
`             || !value.getClass().isInstance(oldValue)`
`              || !value.equals(oldValue) ) ) {`

not handled

`if (value == null && oldValue == null)`

**Comment by jcoleman** [comment]
@RishonLi That case shouldn't throw a NPE because:
- If you look at the parentheses you'll see lines 2-5 of your snipped are only entered if at least one of the two values is not null.
- If both values are null then we don't need to enter the block since nothing has changed.

**Comment by jcoleman** [comment]
Are you running the latest code? What stack trace are you seeing?

**Comment by RishonLi** [comment]
Thanks for your answer.
Yesterday, I pull the latest code with branch tomcat-7.
running throw NPE at the code. Is there any other possible?

**Comment by jcoleman** [comment]
As stated in the README, the `tomcat-7` branch is no longer in use having been merged into master some time ago. You should use `master`.
