### ISSUE TITLE
【suggest】Prevent concurrent session modification

### ISSUE THREAD

**Issue by wenqibo** [jcoleman/tomcat-redis-session-manager#73]
This is my suggest.thank u

**Comment by jcoleman** [comment]
Unfortunately this really isn't feasible given the nature of web applications where simultaneous applications are a reality.

Even if locking were implemented around the sessions, it wouldn't be reasonable to prevent a request from proceeding, which would mean that you'd have to throw an error when the 2nd request that attempts to modify the session finishes. This would mean throwing an exception in the web request after the request has already finished, leading to potentially worse side effects.
