### ISSUE TITLE
malfunction of session-timeout in web.xml

### ISSUE THREAD

**Issue by nagaet** [jcoleman/tomcat-redis-session-manager#81]
I am testing tomcat-redis-session-manager with CentOS6, java 1.8.0_74, and tomcat 7.0.68. 
When I set session-timeout = 60 in $TOMCAT_HOME/conf/web.xml and start a session, TTL of the session-id in Redis is less than 60. It should be around 3600 (= 60 \* 60) since unit of session-timeout is minute. It seems that tomcat-redis-session-manager treats session-timeout as second. I hope it should be corrected to avoid confusion of users.

$ grep session-timeout $TOMCAT_HOME/conf/web.xml
        <session-timeout>60</session-timeout>

when I start session and check the TTL of the session-id in Redis with redis-cli,

127.0.0.1:6379> ttl "2C7784BD28D79DFA64BF1B1BC4958F8D"
(integer) 50   (<---It represents ttl is 50 sec. It should be around 3600 (= 60*60)  )

thanks!!

**Comment by qiuzhihui1990** [comment]
oh, I have the same question,do you solve the problem？

**Comment by qiuzhihui1990** [comment]
I slove it, this is tomcat 7.0.68 's bug,change the tomcat to 68+ is fine。
Bug Fix：https://github.com/apache/tomcat70/commit/0824dcc443e07d0c878d3c3f17ea51668c8fa813

**Comment by nagaet** [comment]
Thanks, it helped me a lot.
