### ISSUE TITLE
how to custom the redis key

### ISSUE THREAD

**Issue by glh1991** [jcoleman/tomcat-redis-session-manager#89]
I have more than one project share the session data, may be I should custom the redis keys to group them I think.  If there are some configs or codes to do that. thx

**Comment by niejian** [comment]
## Copy the following files into the TOMCAT_BASE/lib directory:

tomcat-redis-session-manager-VERSION.jar
jedis-2.5.2.jar
commons-pool2-2.2.jar
## add this in your context.xml
<Valve className="com.orangefunction.tomcat.redissessions.RedisSessionHandlerValve" />
<Manager className="com.orangefunction.tomcat.redissessions.RedisSessionManager"
         host="localhost" 
         port="6379" 
         database="0" 
         maxInactiveInterval="60" 
         sessionPersistPolicies="PERSIST_POLICY_1,PERSIST_POLICY_2,.." 
         sentinelMaster="SentinelMasterName" 
         sentinels="sentinel-host-1:port,sentinel-host-2:port,.."  />
 get it done

**Comment by jcoleman** [comment]
@glh1991 You'll want to look at the Tomcat documentation for `jvmRoute` since that's how the key name works: https://github.com/jcoleman/tomcat-redis-session-manager/blob/master/src/main/java/com/orangefunction/tomcat/redissessions/RedisSessionManager.java#L399
