### ISSUE TITLE
does tomcat-redis-session-manager-1.2-tomcat-7  Compatible  java6?

### ISSUE THREAD

**Issue by niejian** [jcoleman/tomcat-redis-session-manager#95]
when I work with java6 and tomcat 7 it came through
java.lang.UnsupportedClassVersionError: com/radiadesign/catalina/session/RedisSessionHandlerValve : Unsupported major.minor version 51.0。
how can i fix it

**Comment by waming5** [comment]
You packaging the wrong version of the JDK，You should use JDK 1.6
